# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './popup.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(359, 181)
        self.defaultButton = QtWidgets.QPushButton(Dialog)
        self.defaultButton.setGeometry(QtCore.QRect(20, 140, 80, 21))
        self.defaultButton.setObjectName("defaultButton")
        self.okButton = QtWidgets.QPushButton(Dialog)
        self.okButton.setGeometry(QtCore.QRect(140, 140, 80, 21))
        self.okButton.setObjectName("okButton")
        self.resetButton = QtWidgets.QPushButton(Dialog)
        self.resetButton.setGeometry(QtCore.QRect(260, 140, 80, 21))
        self.resetButton.setObjectName("resetButton")
        self.pacLabel = QtWidgets.QLabel(Dialog)
        self.pacLabel.setGeometry(QtCore.QRect(20, 20, 47, 16))
        self.pacLabel.setObjectName("pacLabel")
        self.ghost1Label = QtWidgets.QLabel(Dialog)
        self.ghost1Label.setGeometry(QtCore.QRect(20, 60, 47, 16))
        self.ghost1Label.setObjectName("ghost1Label")
        self.ghost2Label = QtWidgets.QLabel(Dialog)
        self.ghost2Label.setGeometry(QtCore.QRect(20, 100, 47, 16))
        self.ghost2Label.setObjectName("ghost2Label")
        self.pacmanXComboVal = QtWidgets.QComboBox(Dialog)
        self.pacmanXComboVal.setGeometry(QtCore.QRect(110, 20, 41, 21))
        self.pacmanXComboVal.setObjectName("pacmanXComboVal")
        self.pacmanXComboVal.addItem("")
        self.pacmanXComboVal.addItem("")
        self.pacmanXComboVal.addItem("")
        self.pacmanXComboVal.addItem("")
        self.pacmanXComboVal.addItem("")
        self.pacXLabel = QtWidgets.QLabel(Dialog)
        self.pacXLabel.setGeometry(QtCore.QRect(90, 20, 16, 16))
        self.pacXLabel.setObjectName("pacXLabel")
        self.pacYLabel = QtWidgets.QLabel(Dialog)
        self.pacYLabel.setGeometry(QtCore.QRect(160, 20, 16, 16))
        self.pacYLabel.setObjectName("pacYLabel")
        self.pacmanYComboVal = QtWidgets.QComboBox(Dialog)
        self.pacmanYComboVal.setGeometry(QtCore.QRect(180, 20, 41, 21))
        self.pacmanYComboVal.setObjectName("pacmanYComboVal")
        self.pacmanYComboVal.addItem("")
        self.pacmanYComboVal.addItem("")
        self.pacmanYComboVal.addItem("")
        self.pacHeadingLabel = QtWidgets.QLabel(Dialog)
        self.pacHeadingLabel.setGeometry(QtCore.QRect(230, 20, 51, 16))
        self.pacHeadingLabel.setObjectName("pacHeadingLabel")
        self.pacmanHeadingComboVal = QtWidgets.QComboBox(Dialog)
        self.pacmanHeadingComboVal.setGeometry(QtCore.QRect(280, 20, 61, 21))
        self.pacmanHeadingComboVal.setObjectName("pacmanHeadingComboVal")
        self.pacmanHeadingComboVal.addItem("")
        self.pacmanHeadingComboVal.addItem("")
        self.pacmanHeadingComboVal.addItem("")
        self.pacmanHeadingComboVal.addItem("")
        self.ghost1XLabel = QtWidgets.QLabel(Dialog)
        self.ghost1XLabel.setGeometry(QtCore.QRect(90, 60, 16, 16))
        self.ghost1XLabel.setObjectName("ghost1XLabel")
        self.ghost1HeadingLabel = QtWidgets.QLabel(Dialog)
        self.ghost1HeadingLabel.setGeometry(QtCore.QRect(230, 60, 51, 16))
        self.ghost1HeadingLabel.setObjectName("ghost1HeadingLabel")
        self.ghost1XComboVal = QtWidgets.QComboBox(Dialog)
        self.ghost1XComboVal.setGeometry(QtCore.QRect(110, 60, 41, 21))
        self.ghost1XComboVal.setObjectName("ghost1XComboVal")
        self.ghost1XComboVal.addItem("")
        self.ghost1XComboVal.addItem("")
        self.ghost1XComboVal.addItem("")
        self.ghost1XComboVal.addItem("")
        self.ghost1XComboVal.addItem("")
        self.ghost1YLabel = QtWidgets.QLabel(Dialog)
        self.ghost1YLabel.setGeometry(QtCore.QRect(160, 60, 16, 16))
        self.ghost1YLabel.setObjectName("ghost1YLabel")
        self.ghost1HeadingComboVal = QtWidgets.QComboBox(Dialog)
        self.ghost1HeadingComboVal.setGeometry(QtCore.QRect(280, 60, 61, 21))
        self.ghost1HeadingComboVal.setObjectName("ghost1HeadingComboVal")
        self.ghost1HeadingComboVal.addItem("")
        self.ghost1HeadingComboVal.addItem("")
        self.ghost1HeadingComboVal.addItem("")
        self.ghost1HeadingComboVal.addItem("")
        self.ghost1YComboVal = QtWidgets.QComboBox(Dialog)
        self.ghost1YComboVal.setGeometry(QtCore.QRect(180, 60, 41, 21))
        self.ghost1YComboVal.setObjectName("ghost1YComboVal")
        self.ghost1YComboVal.addItem("")
        self.ghost1YComboVal.addItem("")
        self.ghost1YComboVal.addItem("")
        self.ghost2XLabel = QtWidgets.QLabel(Dialog)
        self.ghost2XLabel.setGeometry(QtCore.QRect(90, 100, 16, 16))
        self.ghost2XLabel.setObjectName("ghost2XLabel")
        self.ghost2HeadingLabel = QtWidgets.QLabel(Dialog)
        self.ghost2HeadingLabel.setGeometry(QtCore.QRect(230, 100, 51, 16))
        self.ghost2HeadingLabel.setObjectName("ghost2HeadingLabel")
        self.ghost2XComboVal = QtWidgets.QComboBox(Dialog)
        self.ghost2XComboVal.setGeometry(QtCore.QRect(110, 100, 41, 21))
        self.ghost2XComboVal.setObjectName("ghost2XComboVal")
        self.ghost2XComboVal.addItem("")
        self.ghost2XComboVal.addItem("")
        self.ghost2XComboVal.addItem("")
        self.ghost2XComboVal.addItem("")
        self.ghost2XComboVal.addItem("")
        self.ghost2YLabel = QtWidgets.QLabel(Dialog)
        self.ghost2YLabel.setGeometry(QtCore.QRect(160, 100, 16, 16))
        self.ghost2YLabel.setObjectName("ghost2YLabel")
        self.ghost2HeadingComboVal = QtWidgets.QComboBox(Dialog)
        self.ghost2HeadingComboVal.setGeometry(QtCore.QRect(280, 100, 61, 21))
        self.ghost2HeadingComboVal.setObjectName("ghost2HeadingComboVal")
        self.ghost2HeadingComboVal.addItem("")
        self.ghost2HeadingComboVal.addItem("")
        self.ghost2HeadingComboVal.addItem("")
        self.ghost2HeadingComboVal.addItem("")
        self.ghost2YComboVal = QtWidgets.QComboBox(Dialog)
        self.ghost2YComboVal.setGeometry(QtCore.QRect(180, 100, 41, 21))
        self.ghost2YComboVal.setObjectName("ghost2YComboVal")
        self.ghost2YComboVal.addItem("")
        self.ghost2YComboVal.addItem("")
        self.ghost2YComboVal.addItem("")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Pac-Man Initialization"))
        self.defaultButton.setText(_translate("Dialog", "Use defaults"))
        self.okButton.setText(_translate("Dialog", "OK"))
        self.resetButton.setText(_translate("Dialog", "Reset"))
        self.pacLabel.setText(_translate("Dialog", "Pac-Man:"))
        self.ghost1Label.setText(_translate("Dialog", "Ghost 1:"))
        self.ghost2Label.setText(_translate("Dialog", "Ghost 2:"))
        self.pacmanXComboVal.setItemText(0, _translate("Dialog", "0"))
        self.pacmanXComboVal.setItemText(1, _translate("Dialog", "2"))
        self.pacmanXComboVal.setItemText(2, _translate("Dialog", "4"))
        self.pacmanXComboVal.setItemText(3, _translate("Dialog", "6"))
        self.pacmanXComboVal.setItemText(4, _translate("Dialog", "8"))
        self.pacXLabel.setText(_translate("Dialog", "X:"))
        self.pacYLabel.setText(_translate("Dialog", "Y:"))
        self.pacmanYComboVal.setItemText(0, _translate("Dialog", "0"))
        self.pacmanYComboVal.setItemText(1, _translate("Dialog", "2"))
        self.pacmanYComboVal.setItemText(2, _translate("Dialog", "4"))
        self.pacHeadingLabel.setText(_translate("Dialog", "Heading:"))
        self.pacmanHeadingComboVal.setItemText(0, _translate("Dialog", "north"))
        self.pacmanHeadingComboVal.setItemText(1, _translate("Dialog", "east"))
        self.pacmanHeadingComboVal.setItemText(2, _translate("Dialog", "south"))
        self.pacmanHeadingComboVal.setItemText(3, _translate("Dialog", "west"))
        self.ghost1XLabel.setText(_translate("Dialog", "X:"))
        self.ghost1HeadingLabel.setText(_translate("Dialog", "Heading:"))
        self.ghost1XComboVal.setItemText(0, _translate("Dialog", "0"))
        self.ghost1XComboVal.setItemText(1, _translate("Dialog", "2"))
        self.ghost1XComboVal.setItemText(2, _translate("Dialog", "4"))
        self.ghost1XComboVal.setItemText(3, _translate("Dialog", "6"))
        self.ghost1XComboVal.setItemText(4, _translate("Dialog", "8"))
        self.ghost1YLabel.setText(_translate("Dialog", "Y:"))
        self.ghost1HeadingComboVal.setItemText(0, _translate("Dialog", "north"))
        self.ghost1HeadingComboVal.setItemText(1, _translate("Dialog", "east"))
        self.ghost1HeadingComboVal.setItemText(2, _translate("Dialog", "south"))
        self.ghost1HeadingComboVal.setItemText(3, _translate("Dialog", "west"))
        self.ghost1YComboVal.setItemText(0, _translate("Dialog", "0"))
        self.ghost1YComboVal.setItemText(1, _translate("Dialog", "2"))
        self.ghost1YComboVal.setItemText(2, _translate("Dialog", "4"))
        self.ghost2XLabel.setText(_translate("Dialog", "X:"))
        self.ghost2HeadingLabel.setText(_translate("Dialog", "Heading:"))
        self.ghost2XComboVal.setItemText(0, _translate("Dialog", "0"))
        self.ghost2XComboVal.setItemText(1, _translate("Dialog", "2"))
        self.ghost2XComboVal.setItemText(2, _translate("Dialog", "4"))
        self.ghost2XComboVal.setItemText(3, _translate("Dialog", "6"))
        self.ghost2XComboVal.setItemText(4, _translate("Dialog", "8"))
        self.ghost2YLabel.setText(_translate("Dialog", "Y:"))
        self.ghost2HeadingComboVal.setItemText(0, _translate("Dialog", "north"))
        self.ghost2HeadingComboVal.setItemText(1, _translate("Dialog", "east"))
        self.ghost2HeadingComboVal.setItemText(2, _translate("Dialog", "south"))
        self.ghost2HeadingComboVal.setItemText(3, _translate("Dialog", "west"))
        self.ghost2YComboVal.setItemText(0, _translate("Dialog", "0"))
        self.ghost2YComboVal.setItemText(1, _translate("Dialog", "2"))
        self.ghost2YComboVal.setItemText(2, _translate("Dialog", "4"))

